homeassistant:
# Name of the location where Home Assistant is running
  name: home
# Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
# Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
# metric for Metric, imperial for Imperial
  unit_system: imperial
# Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  customize:
    light.hue_color_lamp_1:
      friendly_name: Living Room
      entity_picture: /local/Hue.png
    light.hue_color_lamp_2:
      friendly_name: Stuart's Room
      entity_picture: /local/Hue.png
    light.hue_color_lamp_3:
      friendly_name: Small Bedroom
      entity_picture: /local/Hue.png
    light.hue_color_lamp_4:
      friendly_name: Bathroom
      entity_picture: /local/Hue.png
    light.hue_color_lamp_5:
      friendly_name: Hallway
      entity_picture: /local/Hue.png
    light.hue_color_lamp_6:
      friendly_name: Kitchen 1
      entity_picture: /local/Hue.png
    light.hue_color_lamp_7:
      friendly_name: Kitchen 2
      entity_picture: /local/Hue.png
    light.hue_color_lamp_8:
      friendly_name: Kitchen 3
      entity_picture: /local/Hue.png
    media_player.roku_yp00en323215:
      friendly_name: Roku Ultra
    media_player.roku_13a174048498:
      hidden: true
    media_player.roku_2l649u000401:
      hidden: true
    media_player.roku_2l64am153737:
      hidden: true
    remote.harmony_hub:
      hidden: true
    light.yard_led_strip:
      icon: mdi:led_strip
    zone.home:
      friendly_name: Home
      hidden: false

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  server_port: !secret server_port
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

media_player:
  - platform: anthemav
    host: !secret anthem_reciever
    name: Anthem MRX 520
  - platform: spotify
    client_id: !secret client_id
    client_secret: !secret client_secret
  - platform: kodi
    host: !secret apt_kodi_ip
    name: Kodi
    
# Weather Prediction
sensor:
  - platform: yr
  - platform: moon
  - platform: yweather
    monitored_conditions:
      - weather
      - weather_current
      - temp_min
      - temp_max
      - wind_speed
      - pressure
      - visibility
      - humidity
      - temperature
  
# Text to speech
tts:
  platform: google

mqtt:
  broker: !secret mqtt_broker_ip
  port: !secret mqtt_broker_port
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_broker_username
  password: !secret mqtt_password
  protocol: !secret mqtt_broker_ver
  tls_insecure: False
      
device_tracker:
  - platform: owntracks
    max_gps_accuracy: 50
    
light:
  - platform: mqtt_json
    name: "Yard LED Strip"
    state_topic: "home/yard"
    command_topic: "home/yard/set"
    effect: true
    effect_list:
      - bpm
      - candy cane
      - confetti
      - cyclon rainbow
      - dots
      - fire
      - glitter
      - juggle
      - lightning
      - noise
      - police all
      - police one
      - rainbow
      - rainbow with glitter
      - ripple
      - sinelon
      - solid
      - twinkle
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0
    
input_slider:
  yard_animation_speed:
    name: Yard Animation Speed
    initial: 300
    min: 1
    max: 300
    step: 10
    
group: !include groups.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
#zone: !include zones.yaml
#script: !include scripts.yaml